[package]
name = "stock-trading-cli-with-async-streams"
version = "0.1.0"
edition = "2021"
authors = ["Ivan Lazarević"]
description = "Stock-Tracking CLI with Async Streams (HFT)"
repository = "https://github.com/ivanbgd/stock-trading-cli-with-async-streams"
license = "MIT"
keywords = ["finance", "fintech", "hft", "stock", "trading"]
categories = ["finance"]

[dependencies]
actix = { version = "0.13" }
actix-rt = { version = "2.9" }
async-std = { version = "1.12", features = ["attributes", "tokio1", "unstable"] }
clap = { version = "4.5.1", features = ["derive"] }
futures = { version = "0.3" }
once_cell = { version = "1.19" }
rayon = { version = "1.9" }
time = { version = "0.3", features = ["formatting", "parsing"] }
tokio = { version = "1.36", features = ["rt", "rt-multi-thread", "macros"] }
yahoo_finance_api = { version = "2.1" }
